const BASE_FONT_SIZE: string = `16px`;

const NAMESPACE: string = `uds`;
const ELEMENT_SEPARATOR: string = `__`;
const MODIFIER_SEPARATOR: string = `--`;

const TRANSITION_INCREMENT: number = 125;

const TRANSITION_DURATION_x0: number = TRANSITION_INCREMENT * 0;
const TRANSITION_DURATION_x1: number = TRANSITION_INCREMENT * 1;
const TRANSITION_DURATION_x2: number = TRANSITION_INCREMENT * 2;
const TRANSITION_DURATION_x3: number = TRANSITION_INCREMENT * 3;
const TRANSITION_DURATION_x4: number = TRANSITION_INCREMENT * 4;
const TRANSITION_DURATION_x5: number = TRANSITION_INCREMENT * 5;
const TRANSITION_DURATION_x6: number = TRANSITION_INCREMENT * 6;
const TRANSITION_DURATION_x7: number = TRANSITION_INCREMENT * 7;
const TRANSITION_DURATION_x8: number = TRANSITION_INCREMENT * 8;
const TRANSITION_DURATION_x9: number = TRANSITION_INCREMENT * 9;
const TRANSITION_DURATION_x10: number = TRANSITION_INCREMENT * 10;
const TRANSITION_DURATION_x11: number = TRANSITION_INCREMENT * 11;
const TRANSITION_DURATION_x12: number = TRANSITION_INCREMENT * 12;

export {
  BASE_FONT_SIZE,
  ELEMENT_SEPARATOR,
  MODIFIER_SEPARATOR,
  NAMESPACE,
  TRANSITION_DURATION_x0,
  TRANSITION_DURATION_x1,
  TRANSITION_DURATION_x2,
  TRANSITION_DURATION_x3,
  TRANSITION_DURATION_x4,
  TRANSITION_DURATION_x5,
  TRANSITION_DURATION_x6,
  TRANSITION_DURATION_x7,
  TRANSITION_DURATION_x8,
  TRANSITION_DURATION_x9,
  TRANSITION_DURATION_x10,
  TRANSITION_DURATION_x11,
  TRANSITION_DURATION_x12
};
